bookshop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls'))
]

library/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('books/', list_books, name="list_books"),
    path("books_detail/<int:pk>/", BookDetail.as_view(), name="book_detail"),
    path('', home, name='home'),
    path('login/', login_view, name='login_view'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('cart/', cart_detail, name='cart_detail'),
    path('cart/add/<int:book_id>', add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:book_id>', remove_item, name='remove_item'),
    path('reduce_item/<int:book_id>', reduce_item, name='reduce_item'),
    path('add_more_books/<int:book_id>', add_more_books, name='add_more_books'),
    path('blogs/', blog, name='blogs'),
    path('more/', author, name='more'),
    path('author_books/<int:author_id>/books/', author_books, name='author_books'),
    path('profile/', profile_view, name='profile_view'),
    path('profile/update/', profile_update, name='profile_update'),
    path('forgot_password/', forgot_password, name='forgot_password'),
    path('restore_password/', restore_password, name='restore_password')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/models.py
from datetime import timedelta
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class ChoiceField(models.TextChoices):
    HORROR = 'horror', 'Horror'
    DRAMA = 'drama', 'Drama'
    DETECTIVE = 'detective', 'Detective'
    THRILLER = 'thriller', 'Thriller'
    HISTORICAL = 'historical', 'Historical'
    FANTASY = 'fantasy', 'Fantasy'
    NOVEL = 'novel', 'Novel'

class Author(models.Model):
    author_image = models.ImageField(upload_to='author_image/')
    fullname = models.CharField(max_length=200)
    about = models.TextField(null=True, blank=True)
    date_birth = models.DateField()

    class Meta:
        db_table = 'author'

    def __str__(self):
        return self.fullname

class Book(models.Model):
    cover_image = models.ImageField(upload_to='book_covers/')
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=7, decimal_places=2)  # Increased max_digits for flexibility
    count = models.PositiveIntegerField(default=1)  # Ensuring non-negative count
    genre = models.CharField(choices=ChoiceField.choices, max_length=20)  # Added max_length
    about = models.TextField()
    add_to_cart = models.BooleanField(default=False)

    class Meta:
        db_table = 'book'

    def __str__(self):
        return f"{self.title} by {self.author.fullname}"


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    took_date = models.DateField(default=timezone.now)
    book_count = models.PositiveIntegerField(default=1)

    class Meta:
        db_table = 'cart'

    def __str__(self):
        return f"{self.user.username}'s Cart - {self.book.title}"

    def total_price(self):
        return self.book.price * self.book_count

class Status(models.TextChoices):
    PENDING = 'pending', 'Pending'
    SHIPPED = 'shipped', 'Shipped'
    DELIVERED = 'delivered', 'Delivered'
    CANCELLED = 'cancelled', 'Cancelled'

class OrderDetail(models.Model):
    quantity_sold = models.PositiveIntegerField()
    unit_price = models.DecimalField(max_digits=7, decimal_places=2)
    order_date = models.DateTimeField(auto_now=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    status = models.CharField(choices=Status.choices, max_length=20)

    class Meta:
        db_table = 'order_details'

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_details = models.ManyToManyField(OrderDetail)

    class Meta:
        db_table = 'orders'

    def __str__(self):
        return f"Order {self.id} by {self.user.username}"

class Blog(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=30)
    about = models.TextField()
    created = models.DateField(auto_now=True)
    updated = models.DateField(auto_now_add=True)
    image = models.ImageField(upload_to='blog_images/')

    class Meta:
        db_table = 'blog'
        ordering = ['-id']

    def __str__(self):
        return self.title

def time_default():
    return timezone.now() + timedelta(minutes=10)

class Code(models.Model):
    code_number = models.CharField(max_length=200)
    user = models.ForeignKey(User, models.CASCADE, related_name='code_user')
    expired_data = models.DateTimeField(default=time_default)

library/forms.py
from django.utils import timezone
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from library.models import Code


class BookForm(forms.Form):
    title = forms.CharField(max_length=200)
    author = forms.CharField(max_length=200)
    count = forms.IntegerField(min_value=1)


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput, label="Password")
    password_confirmation = forms.CharField(widget=forms.PasswordInput, label="Confirm Password")

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirmation = cleaned_data.get("password_confirmation")

        if password and password_confirmation and password != password_confirmation:
            raise forms.ValidationError("Passwords do not match.")
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

class ProfileForm(forms.ModelForm):
    change_password = forms.CharField(max_length=255, widget=forms.PasswordInput)
    confirm_password = forms.CharField(max_length=255, widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name']

    def clean(self):
        cleaned_data = super().clean()
        change_password = cleaned_data.get('change_password')
        confirm_password = cleaned_data.get('confirm_password')

        if change_password != confirm_password:
            raise forms.ValidationError('Password do not match!')
        return cleaned_data


class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))

    def clean_email(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        if not User.objects.filter(email=email).exists():
            raise ValidationError('Email Does Not Exist')
        return email

class RestorePassword(forms.Form):
    username = forms.CharField(max_length=255)
    code = forms.CharField(max_length=4)
    code = forms.CharField(max_length=200)
    password = forms.CharField(max_length=255, widget=forms.PasswordInput)
    re_password = forms.CharField(max_length=255, widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        code = cleaned_data.get('code')
        password = cleaned_data.get('password')
        re_password = cleaned_data.get('re_password')
        user = User.objects.filter(username=username).first()

        if not user:
            raise ValidationError('User Not Found')

        if not Code.objects.filter(user=user, code_number=code, expired_data__gt=timezone.now()):
            raise ValidationError(f'Code is incorrect {timezone.now()}')

        if password != re_password:
            raise forms.ValidationError('Password do not match!')

        return cleaned_data

    def update(self):
        user = User.objects.filter(username=self.cleaned_data.get('username')).first()
        user.set_password(self.cleaned_data.get('password'))
        user.save()
        user.save()

library/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout, get_user, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.shortcuts import redirect, render, get_object_or_404
from django.db.models import Q
from .models import *
from .forms import LoginForm, RegistrationForm, ProfileForm, ForgotPasswordForm, RestorePassword
from django.views.generic.detail import DetailView
from django.contrib.auth.models import User
from .service import send_html_email, send_email_in_thread


class BookDetail(DetailView):
    model = Book
    template_name = 'book/book_detail.html'
    context_object_name = 'book'


class AuthorDetail(DetailView):
    model = Author
    template_name = 'book/book_detail.html'
    context_object_name = 'author'


def author(request):
    author = Author.objects.all()
    return render(request, 'authors/more.html', {
        "more": author
    })


def blog(request):
    blogs = Blog.objects.all()
    return render(request, 'blogs/blogs.html', {
        "blogs": blogs
    })


def list_books(request):
    search = request.GET.get("search", "")
    filter_ = request.GET.get("order", "-id")

    books = Book.objects.all()

    if search:
        books = books.filter(
            Q(title__icontains=search)
        )
    books = books.order_by(filter_)

    return render(request, "book/books.html", {
        "books": books,
        "search": search,
        "filter_": filter_,
    })


# def create_book(request):
#     if request.method == 'GET':
#         form = BookForm()
#     else:
#         form = BookForm(request.POST)
#         if form.is_valid():
#             data = form.cleaned_data
#             book = Book.objects.create(
#                 title=data['title'],
#                 author=data['author'],
#                 count=data['count']
#             )
#             return redirect('books')
#
#     return render(request, 'book/book-create.html', {
#         "form": form,
#     })


def home(request):
    return render(request, 'main/home.html', )


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('home')
            messages.error(request, 'Username or Password is incorrect')
        return render(request, 'login/login.html', {
            "form": form
        })
    form = LoginForm()
    return render(request, 'login/login.html', {
        "form": form
    })


def register_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('login_view')
        return render(request, 'login/register.html', {
            "form": form
        })
    form = RegistrationForm()
    return render(request, 'login/register.html', {
        "form": form
    })


def logout_view(request):
    logout(request)
    return redirect('login_view')


@login_required
def cart_detail(request):
    cart_items = Cart.objects.filter(user_id=request.user)
    total_price = sum(item.total_price() for item in cart_items)

    return render(request, 'cart/cart.html', {
        "cart_items": cart_items,
        "total_price": total_price
    })


@login_required
def add_to_cart(request, book_id):
    book = get_object_or_404(Book, id=book_id)
    user_id = request.user
    cart_item, created = Cart.objects.get_or_create(user=user_id, book=book)
    if not created:
        cart_item.book_count += 1
        cart_item.save()

    return redirect('list_books')


@login_required
def remove_item(request, book_id):
    cart_item = get_object_or_404(Cart, book_id=book_id, user_id=request.user)
    cart_item.delete()

    return redirect('cart_detail')


@login_required
def reduce_item(request, book_id):
    cart_item = get_object_or_404(Cart, book_id=book_id, user=request.user)
    if cart_item.book_count > 1:
        cart_item.book_count -= 1
        cart_item.save()
        return redirect('cart_detail')
    cart_item.delete()
    return redirect('cart_detail')


@login_required
def add_more_books(request, book_id):
    cart_item = get_object_or_404(Cart, book_id=book_id, user=request.user)
    book = get_object_or_404(Book, id=book_id)
    try:
        if cart_item.book_count + 1 > book.count:
            return redirect('cart_detail')
        cart_item.book_count += 1
        cart_item.save()
        return redirect('cart_detail')
    except ValidationError:
        messages.error(request, 'Not enough in stock')


def author_books(request, author_id):
    author = get_object_or_404(Author, id=author_id)
    books = Book.objects.filter(author_id=author_id)
    return render(request, 'book/author_books.html', {
        "author": author,
        "book": books
    })


@login_required
def profile_view(request):
    user = get_user(request)
    return render(request, 'users/profile.html', {
        "user": user
    })

@login_required
def profile_update(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            user = form.save(commit=False)
            change_password = form.cleaned_data.get('change_password')
            if change_password:
                user.set_password(change_password)
                update_session_auth_hash(request, user)
            user.save()
            return redirect('profile_view')
    form = ProfileForm(instance=request.user)
    return render(request, 'users/profile_update.html', {'form': form})


def forgot_password(request):
    if request.method == 'POST':
        form = ForgotPasswordForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            user = User.objects.filter(email=email).first()
            if user:
                send_email_in_thread(user.email, user)
                return render(request, 'reset_password/password_reset_confirm.html')
            form.add_error('email', 'User not found')  # Optional error handling
        return render(request, 'reset_password/reset_password.html', {"form": form})
    form = ForgotPasswordForm()
    return render(request, 'reset_password/reset_password.html', {"form": form})


def restore_password(request):
    if request.method == 'POST':
        form = RestorePassword(request.POST)
        if form.is_valid():
            form.update()
            return render(request, 'reset_password/password_reset_complete.html', {"form" : form})
        return render(request, 'reset_password/password_reset_email.html', {"form" : form })
    form = RestorePassword()
    return render(request, 'reset_password/password_reset_email.html', {"form": form})

library/templates/users/profile.html
{% extends 'main.html' %}
{% block content %}
    <section class="user-profile">
        <div class="container p-5 my-5">
            <div class="row d-flex align-items-center justify-content-center g-5">
                <div class="col-4 d-flex align-items-center justify-content-center flex-column">
                    <div class="profile-img">
                        <img src="/static/images/profile.png" class="profile_img">
                    </div>
                    <h1 class="text-center" style="text-transform: capitalize">{{ user.username }}'s Profile</h1>
                </div>
                <div class="col-6 d-flex align-items-center justify-content-center flex-column">
                    <h2>{{ user.first_name }}</h2>
                    <h2>{{ user.last_name }}</h2>
                    <a class="btn btn-primary" href="{% url 'profile_update' %}">Edit Profile</a>
                </div>
            </div>

        </div>
    </section>
{% endblock %}

library/templates/users/profile_update.html
{% extends 'main.html' %}{% block content %}    <section class="user-profile-update">        <div class="container p-5">            <h1>Edit Profile</h1>            <form method="post" class="needs-validation" novalidate>                {% csrf_token %}                <div class="mb-3">                    <label for="id_username" class="form-label">Username</label>                    <input type="text" class="form-control" id="id_username" name="username"                           value="{{ form.username.value|default:'' }}" required>                </div>                <div class="mb-3">                    <label for="id_first_name" class="form-label">First Name</label>                    <input type="text" class="form-control" id="id_first_name" name="first_name"                           value="{{ form.first_name.value|default:'' }}" required>                </div>                <div class="mb-3">                    <label for="id_last_name" class="form-label">Last Name</label>                    <input type="text" class="form-control" id="id_last_name" name="last_name"                           value="{{ form.last_name.value|default:'' }}" required>                </div>                <div class="mb-3">                    <label for="id_change_password" class="form-label">New Password</label>                    <input type="password" class="form-control" id="id_change_password" name="change_password">                </div>                <div class="mb-3">                    <label for="id_confirm_password" class="form-label">Confirm Password</label>                    <input type="password" class="form-control" id="id_confirm_password" name="confirm_password">                </div>                <button type="submit" class="btn btn-primary">Update Profile</button>            </form>        </div>    </section>{% endblock %}

library/templates/users/users.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            list-style: none;
        }

        h1 {
            text-align: center;
        }

        ul li a {
            display: flex;
            margin-bottom: 20px;
            text-align: center;
            text-decoration: none;
            font-size: 20px;
            color: black;
            justify-content: center;
            align-items: center;
            gap: 10px;
        }

        form {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        form input {
            width: 30%;
            padding: 15px;
            font-size: 20px;
            margin-bottom: 20px;
        }

        form button {
            width: 30%;
            padding: 10px;
            font-size: 20px;
        }


    </style>
</head>
<body>
    <h1>Users List</h1>
    <ul>
        {% for user in users %}
        <li><a href="#"><h4>Fullname:</h4> {{user.firstname}} {{user.lastname}} 
            <h4>Role:</h4> {{ user.role }} </a></li>
        {% endfor %}
    </ul>

    <form>
        <input name="search" value="{{search}}" placeholder="Search Book">
        <button type="submit">Search</button>
    </form>
</body>
</html>